// Users types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SCORE_USUARIO = "SET_SCORE_USUARIO";

// Candidate types
export const SET_DADOS_CANDIDATOS = "SET_DADOS_CANDIDATOS";
export const SET_SCORE_CANDIDATOS = "SET_SCORE_CANDIDATOS";
export const CANDIDATOS_CARREGANDO = "CANDIDATOS_CARREGANDO";
export const CANDIDATOS_CARREGADOS = "CANDIDATOS_CARREGADOS";

// Perguntas types
export const PERGUNTAS_CARREGANDO = "PERGUNTAS_CARREGANDO";
export const PERGUNTAS_CARREGADAS = "PERGUNTAS_CARREGADAS";
