// Users types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SCORE_USUARIO = "SET_SCORE_USUARIO";

// Candidate types
export const SET_DADOS_CANDIDATOS = "SET_DADOS_CANDIDATOS";
export const SET_SCORE_CANDIDATOS = "SET_SCORE_CANDIDATOS";
export const SET_SCORE_CANDIDATO_POR_TEMA = "SET_SCORE_CANDIDATOS_POR_TEMA";
export const CANDIDATOS_CARREGANDO = "CANDIDATOS_CARREGANDO";
export const CANDIDATOS_CARREGADOS = "CANDIDATOS_CARREGADOS";
export const SET_TOTAL_RESPONDERAM_ESTADO = "SET_TOTAL_RESPONDERAM_ESTADO";
export const SET_TOTAL_RESPOSTAS_ESTADO = "SET_TOTAL_RESPOSTAS_ESTADO";
export const SET_TOTAL_RESPONDERAM_PARTIDO = "SET_TOTAL_RESPONDERAM_PARTIDO";
export const SET_TOTAL_RESPOSTAS_PARTIDO = "SET_TOTAL_RESPOSTAS_PARTIDO";
export const SET_DADOS_CANDIDATO = "SET_DADOS_CANDIDATO";
export const SET_DADOS_CANDIDATO_POR_CPF = "SET_DADOS_CANDIDATO_POR_CPF";
export const SET_CANDIDATOS_FILTRADOS = "SET_CANDIDATOS_FILTRADOS";
export const SET_CANDIDATOS_RANQUEADOS = "SET_CANDIDATOS_RANQUEADOS";
export const SET_PARTIDOS = "SET_PARTIDOS";
export const SET_PAGINACAO = "SET_PAGINACAO";
export const SET_CANDIDATOS_FILTRANDO = "SET_CANDIDATOS_FILTRANDO";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const SET_TOTAL_ELEITOS_ESTADO = "SET_TOTAL_ELEITOS_ESTADO";
export const SET_TOTAL_ELEITOS_PARTIDO = "SET_TOTAL_ELEITOS_PARTIDO";
export const SET_VER_TODOS_ELEITOS = "SET_VER_TODOS_ELEITOS";

// Perguntas types
export const PERGUNTAS_CARREGANDO = "PERGUNTAS_CARREGANDO";
export const SET_DADOS_PERGUNTAS = "SET_DADOS_PERGUNTAS";
export const SET_INDEX_PERGUNTA = "SET_INDEX_PERGUNTA";
export const SET_TEMA = "SET_TEMA";
export const SET_FILTRO_CANDIDATOS = "SET_FILTRO_CANDIDATOS";
export const SET_MOSTRAR_TODOS_CANDIDATOS = "SET_MOSTRAR_TODOS_CANDIDATOS";
export const SET_VAMOS_COMECAR = "SET_VAMOS_COMECAR";
export const EXIBE_PERGUNTAS = "EXIBE_PERGUNTAS";
export const ESCONDE_PERGUNTAS = "ESCONDE_PERGUNTAS";
export const SET_CONTINUAR_RESPONDENDO = "SET_CONTINUAR_RESPONDENDO";

// Votacoes types
export const SET_DADOS_VOTACOES = "SET_DADOS_VOTACOES";
export const VOTACOES_CARREGANDO = "VOTACOES_CARREGANDO";
